pipeline{
    agent any
    environment{
        CI = 'true'
    }

    stages{
        stage('install npm'){
            steps{
                sh 'npm install'
            }

        }
        stage('test'){
            steps{
                sh './jenkins/scripts/test.sh'
            }

        }


    }

}
